## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      client-secret: ENC(gPFcUOmJm8WqM3k3eSqS0Q==)
      scope: server
      ignore-urls:
        - '/actuator/**'
        - '/v2/api-docs'
        - '/service/**'
        - '/editor-app/**'
        - '/task/view/*'
        - '/process/resource/**'
        - '/modeler.html'
spring:
  autoconfigure:
    exclude: org.activiti.spring.boot.SecurityAutoConfiguration
  activiti:
    check-process-definitions: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
